//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPeopleServiceApplication.AnimalDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnimalDataServiceReference.IAnimalDataService")]
    public interface IAnimalDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/GetAnimal", ReplyAction="http://tempuri.org/IAnimalDataService/GetAnimalResponse")]
        string GetAnimal(string animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/GetAnimal", ReplyAction="http://tempuri.org/IAnimalDataService/GetAnimalResponse")]
        System.Threading.Tasks.Task<string> GetAnimalAsync(string animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/GetAnimals", ReplyAction="http://tempuri.org/IAnimalDataService/GetAnimalsResponse")]
        System.Collections.ObjectModel.ObservableCollection<AnimalDataEntitities.Animal> GetAnimals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/GetAnimals", ReplyAction="http://tempuri.org/IAnimalDataService/GetAnimalsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AnimalDataEntitities.Animal>> GetAnimalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/AddAnimal", ReplyAction="http://tempuri.org/IAnimalDataService/AddAnimalResponse")]
        void AddAnimal(AnimalDataEntitities.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnimalDataService/AddAnimal", ReplyAction="http://tempuri.org/IAnimalDataService/AddAnimalResponse")]
        System.Threading.Tasks.Task AddAnimalAsync(AnimalDataEntitities.Animal animal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnimalDataServiceChannel : WCFPeopleServiceApplication.AnimalDataServiceReference.IAnimalDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnimalDataServiceClient : System.ServiceModel.ClientBase<WCFPeopleServiceApplication.AnimalDataServiceReference.IAnimalDataService>, WCFPeopleServiceApplication.AnimalDataServiceReference.IAnimalDataService {
        
        public AnimalDataServiceClient() {
        }
        
        public AnimalDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnimalDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnimalDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAnimal(string animal) {
            return base.Channel.GetAnimal(animal);
        }
        
        public System.Threading.Tasks.Task<string> GetAnimalAsync(string animal) {
            return base.Channel.GetAnimalAsync(animal);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<AnimalDataEntitities.Animal> GetAnimals() {
            return base.Channel.GetAnimals();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AnimalDataEntitities.Animal>> GetAnimalsAsync() {
            return base.Channel.GetAnimalsAsync();
        }
        
        public void AddAnimal(AnimalDataEntitities.Animal animal) {
            base.Channel.AddAnimal(animal);
        }
        
        public System.Threading.Tasks.Task AddAnimalAsync(AnimalDataEntitities.Animal animal) {
            return base.Channel.AddAnimalAsync(animal);
        }
    }
}
